/*
 * ExceptionDisplayPanel.java
 *
 * Created on January 2, 2007, 10:24 AM
 */

package com.blazartech.util.gui.exception;

import javax.swing.JPanel;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 * A panel to show exception information.
 * @author  Dr. Scott E. Aaron
 * @version $Id: ExceptionDisplayPanel.java 21 2015-04-23 19:41:38Z aar1069 $
 */

/* $Log: ExceptionDisplayPanel.java,v $
/* Revision 1.3  2007/07/17 19:08:45  AAR1069
/* Use a wrapping label
/*
/* Revision 1.2  2007/01/02 19:28:52  aar1069
/* Added documentation.
/*
 ************************************************************************/
@Component
@Scope("prototype")
public class ExceptionDisplayPanel extends JPanel {
    
    /** Creates new form ExceptionDisplayPanel */
    public ExceptionDisplayPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _summaryPanel = new javax.swing.JPanel();
        _summaryLabel = new com.blazartech.util.gui.exception.WrappingLabel();
        _detailsPanel = new javax.swing.JPanel();
        _detailScroller = new javax.swing.JScrollPane();
        _detailText = new javax.swing.JTextArea();

        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        _summaryPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        _summaryLabel.setMaxWidth(500);
        _summaryPanel.add(_summaryLabel);

        add(_summaryPanel);

        _detailsPanel.setLayout(new java.awt.BorderLayout());

        _detailText.setColumns(45);
        _detailText.setEditable(false);
        _detailText.setRows(15);
        _detailScroller.setViewportView(_detailText);

        _detailsPanel.add(_detailScroller, java.awt.BorderLayout.CENTER);

        add(_detailsPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
        if (evt.getPropertyName().equals("exception")) {
            handleUpdateException();
        }
    }//GEN-LAST:event_formPropertyChange
    
    private String getStackTrace(Throwable e) {
        String trace = e.getClass().toString() + ": " + e.getMessage() + "\n";
        for (StackTraceElement el : e.getStackTrace()) {
            trace += "    " + el.toString() + "\n";
        }
        if (e.getCause() != null) {
            trace += "caused by " + getStackTrace(e.getCause());
        }
        return trace;
    }
    
    private void handleUpdateException() {
        _summaryLabel.setText("Exception: " + getException().getMessage());
        _detailText.setText(getStackTrace(getException()));
        _detailText.setCaretPosition(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane _detailScroller;
    private javax.swing.JTextArea _detailText;
    private javax.swing.JPanel _detailsPanel;
    private com.blazartech.util.gui.exception.WrappingLabel _summaryLabel;
    private javax.swing.JPanel _summaryPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * Holds value of property exception.
     */
    private Exception exception;

    /**
     * Getter for property exception.
     * @return Value of property exception.
     */
    public Exception getException() {
        return this.exception;
    }

    /**
     * Setter for property exception.
     * @param exception New value of property exception.
     */
    public void setException(Exception exception) {
        Exception oldException = this.exception;
        this.exception = exception;
        firePropertyChange ("exception", oldException, exception);
    }
    
}
